columns:
    id:
        label: Id
        name: id
        type: integer
        builder: simple
        options:
            listable: true
            editable: false
            sortable: true
            filterable: true
    name:
        label: Name
        name: name
        type: string
        builder: simple
        options:
            listable: true
            editable: true
            sortable: true
            filterable: true
actions:
    new:
        route: admin_exams_types_new
        extends: new
    edit:
        route: admin_exams_types_edit
        extends: edit
    delete:
        route: admin_exams_types_delete
        extends: delete
